# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20180618123521) do

  create_table "cuestionarios", force: :cascade do |t|
    t.string "nombre"
    t.date "fecha"
    t.date "FdN"
    t.string "direccion"
    t.boolean "sexo"
    t.string "email"
    t.string "telefono"
    t.string "movil"
    t.string "profesion"
    t.decimal "altura"
    t.decimal "peso"
    t.string "motivos"
    t.boolean "especialistas"
    t.boolean "dieta"
    t.boolean "intolerancia"
    t.string "detalles_1"
    t.integer "limites"
    t.string "otro_1"
    t.string "problema1"
    t.string "p1"
    t.string "p2"
    t.string "p3"
    t.string "problema2"
    t.string "p4"
    t.string "p5"
    t.string "p6"
    t.string "problema3"
    t.string "p7"
    t.string "p8"
    t.string "p9"
    t.string "problema4"
    t.string "p10"
    t.string "p11"
    t.string "p12"
    t.text "otro_2"
    t.string "medicacion1"
    t.string "m1"
    t.string "m2"
    t.string "m3"
    t.string "m4"
    t.boolean "m5"
    t.boolean "m6"
    t.string "medicacion2"
    t.string "m7"
    t.string "m8"
    t.string "m9"
    t.string "m10"
    t.boolean "m11"
    t.boolean "m12"
    t.string "medicacion3"
    t.string "m13"
    t.string "m14"
    t.string "m15"
    t.string "m16"
    t.boolean "m17"
    t.boolean "m18"
    t.text "otro_3"
    t.string "suplemento1"
    t.string "s1"
    t.string "s2"
    t.boolean "s3"
    t.boolean "s4"
    t.string "suplemento2"
    t.string "s5"
    t.string "s6"
    t.boolean "s7"
    t.boolean "s8"
    t.string "suplemento3"
    t.string "s9"
    t.string "s10"
    t.boolean "s11"
    t.boolean "s12"
    t.text "otro_4"
    t.string "madre"
    t.string "padre"
    t.string "abuela_mat"
    t.string "abuela_pat"
    t.string "abuelo_mat"
    t.string "abuelo_pat"
    t.string "hermanos"
    t.string "hermanas"
    t.string "tios"
    t.string "tias"
    t.string "ninos"
    t.string "sobrinos"
    t.integer "activa"
    t.string "ejercicio1"
    t.string "e1"
    t.string "e2"
    t.string "ejercicio2"
    t.string "e3"
    t.string "e4"
    t.string "ejercicio3"
    t.string "e5"
    t.string "e6"
    t.text "otro_5"
    t.boolean "fumas1"
    t.integer "fumas2"
    t.boolean "fumado"
    t.string "alcol1"
    t.string "alcol2"
    t.integer "alergia1"
    t.text "alergia2"
    t.string "habitos1"
    t.string "habitos2"
    t.string "habitos3"
    t.string "habitos4"
    t.string "galletas_tartas_bolleria"
    t.string "leche"
    t.string "huevos"
    t.string "chocolates_dulces"
    t.string "carne_roja"
    t.string "carne_blanca"
    t.string "pescado_blanco"
    t.string "pezcado_azul"
    t.string "carne_procesada"
    t.string "pan"
    t.string "te"
    t.string "cafe"
    t.string "refresco_lata"
    t.string "agua"
    t.string "verdura"
    t.string "ensalada"
    t.integer "tick"
    t.boolean "pecho"
    t.boolean "dieta_sana"
    t.integer "motivacion"
    t.text "desayuno1"
    t.text "desayuno2"
    t.text "desayuno3"
    t.text "almuerzo"
    t.text "almuerzo2"
    t.text "almuerzo3"
    t.text "cena1"
    t.text "cena2"
    t.text "cena3"
    t.text "snacks1"
    t.text "snacks2"
    t.text "snacks3"
    t.text "bebidas1"
    t.text "bebidas2"
    t.text "bebidas3"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "formularios", force: :cascade do |t|
    t.string "nombre"
    t.date "fecha"
    t.date "FdN"
    t.string "direccion"
    t.boolean "sexo"
    t.string "email"
    t.string "telefono"
    t.string "movil"
    t.string "profesion"
    t.decimal "altura"
    t.decimal "peso"
    t.string "motivos"
    t.boolean "especialistas"
    t.boolean "dieta"
    t.boolean "intolerancia"
    t.string "detalles_1"
    t.string "limites"
    t.string "otro_1"
    t.string "problema1"
    t.string "p1"
    t.string "p2"
    t.string "p3"
    t.string "problema2"
    t.string "p4"
    t.string "p5"
    t.string "p6"
    t.string "problema3"
    t.string "p7"
    t.string "p8"
    t.string "p9"
    t.string "problema4"
    t.string "p10"
    t.string "p11"
    t.string "p12"
    t.text "otro_2"
    t.string "medicacion1"
    t.string "m1"
    t.string "m2"
    t.string "m3"
    t.string "m4"
    t.boolean "m5"
    t.boolean "m6"
    t.string "medicacion2"
    t.string "m7"
    t.string "m8"
    t.string "m9"
    t.string "m10"
    t.boolean "m11"
    t.boolean "m12"
    t.string "medicacion3"
    t.string "m13"
    t.string "m14"
    t.string "m15"
    t.string "m16"
    t.boolean "m17"
    t.boolean "m18"
    t.text "otro_3"
    t.string "suplemento1"
    t.string "s1"
    t.string "s2"
    t.boolean "s3"
    t.boolean "s4"
    t.string "suplemento2"
    t.string "s5"
    t.string "s6"
    t.boolean "s7"
    t.boolean "s8"
    t.string "suplemento3"
    t.string "s9"
    t.string "s10"
    t.boolean "s11"
    t.boolean "s12"
    t.text "otro_4"
    t.string "madre"
    t.string "padre"
    t.string "abuela_mat"
    t.string "abuela_pat"
    t.string "abuelo_mat"
    t.string "abuelo_pat"
    t.string "hermanos"
    t.string "hermanas"
    t.string "tios"
    t.string "tias"
    t.string "ninos"
    t.string "sobrinos"
    t.string "activa"
    t.string "ejercicio1"
    t.string "e1"
    t.string "e2"
    t.string "ejercicio2"
    t.string "e3"
    t.string "e4"
    t.string "ejercicio3"
    t.string "e5"
    t.string "e6"
    t.text "otro_5"
    t.boolean "fumas1"
    t.integer "fumas2"
    t.boolean "fumado"
    t.string "alcol1"
    t.string "alcol2"
    t.string "alergia1"
    t.text "alergia2"
    t.string "habitos1"
    t.string "habitos2"
    t.string "habitos3"
    t.string "habitos4"
    t.string "galletas_tartas_bolleria"
    t.string "leche"
    t.string "huevos"
    t.string "chocolates_dulces"
    t.string "carne_roja"
    t.string "carne_blanca"
    t.string "pescado_blanco"
    t.string "pezcado_azul"
    t.string "carne_procesada"
    t.string "pan"
    t.string "te"
    t.string "cafe"
    t.string "refresco_lata"
    t.string "agua"
    t.string "verdura"
    t.string "ensalada"
    t.string "tick"
    t.boolean "pecho"
    t.boolean "dieta_sana"
    t.integer "motivacion"
    t.text "desayuno1"
    t.text "desayuno2"
    t.text "desayuno3"
    t.text "almuerzo"
    t.text "almuerzo2"
    t.text "almuerzo3"
    t.text "cena1"
    t.text "cena2"
    t.text "cena3"
    t.text "snacks1"
    t.text "snacks2"
    t.text "snacks3"
    t.text "bebidas1"
    t.text "bebidas2"
    t.text "bebidas3"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "refresco_light"
    t.string "fruta"
  end

  create_table "questionnaires", force: :cascade do |t|
    t.string "name"
    t.date "dob"
    t.string "q1"
    t.string "q2"
    t.string "q3"
    t.text "q4"
    t.text "q5"
    t.text "q6"
    t.boolean "q7"
    t.boolean "q8"
    t.boolean "q9"
    t.integer "q10"
    t.integer "q11"
    t.integer "q12"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "questions", force: :cascade do |t|
    t.string "title"
    t.string "type"
    t.integer "survey_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["survey_id"], name: "index_questions_on_survey_id"
  end

  create_table "surveys", force: :cascade do |t|
    t.string "title"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "users", force: :cascade do |t|
    t.string "email", default: "", null: false
    t.string "encrypted_password", default: "", null: false
    t.string "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer "sign_in_count", default: 0, null: false
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.string "current_sign_in_ip"
    t.string "last_sign_in_ip"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.boolean "admin"
    t.index ["email"], name: "index_users_on_email", unique: true
    t.index ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true
  end

end
