class CreateCuestionarios < ActiveRecord::Migration[5.1]
  def change
    create_table :cuestionarios do |t|
      t.string :nombre
      t.date :fecha
      t.date :FdN
      t.string :direccion
      t.boolean :sexo
      t.string :email
      t.string :telefono
      t.string :movil
      t.string :profesion
      t.decimal :altura
      t.decimal :peso
      t.string :motivos
      t.boolean :especialistas
      t.boolean :dieta
      t.boolean :intolerancia
      t.string :detalles_1
      t.integer :limites
      t.string :otro_1
      t.string :problema1
      t.string :p1
      t.string :p2
      t.string :p3
      t.string :problema2
      t.string :p4
      t.string :p5
      t.string :p6
      t.string :problema3
      t.string :p7
      t.string :p8
      t.string :p9
      t.string :problema4
      t.string :p10
      t.string :p11
      t.string :p12
      t.text :otro_2
      t.string :medicacion1
      t.string :m1
      t.string :m2
      t.string :m3
      t.string :m4
      t.boolean :m5
      t.boolean :m6
      t.string :medicacion2
      t.string :m7
      t.string :m8
      t.string :m9
      t.string :m10
      t.boolean :m11
      t.boolean :m12
      t.string :medicacion3
      t.string :m13
      t.string :m14
      t.string :m15
      t.string :m16
      t.boolean :m17
      t.boolean :m18
      t.text :otro_3
      t.string :suplemento1
      t.string :s1
      t.string :s2
      t.boolean :s3
      t.boolean :s4
      t.string :suplemento2
      t.string :s5
      t.string :s6
      t.boolean :s7
      t.boolean :s8
      t.string :suplemento3
      t.string :s9
      t.string :s10
      t.boolean :s11
      t.boolean :s12
      t.text :otro_4
      t.string :madre
      t.string :padre
      t.string :abuela_mat
      t.string :abuela_pat
      t.string :abuelo_mat
      t.string :abuelo_pat
      t.string :hermanos
      t.string :hermanas
      t.string :tios
      t.string :tias
      t.string :ninos
      t.string :sobrinos
      t.integer :activa
      t.string :ejercicio1
      t.string :e1
      t.string :e2
      t.string :ejercicio2
      t.string :e3
      t.string :e4
      t.string :ejercicio3
      t.string :e5
      t.string :e6
      t.text :otro_5
      t.boolean :fumas1
      t.integer :fumas2
      t.boolean :fumado
      t.string :alcol1
      t.string :alcol2
      t.integer :alergia1
      t.text :alergia2
      t.string :habitos1
      t.string :habitos2
      t.string :habitos3
      t.string :habitos4
      t.string :galletas_tartas_bolleria
      t.string :leche
      t.string :huevos
      t.string :chocolates_dulces
      t.string :carne_roja
      t.string :carne_blanca
      t.string :pescado_blanco
      t.string :pezcado_azul
      t.string :carne_procesada
      t.string :pan
      t.string :te
      t.string :cafe
      t.string :refresco_lata
      t.string :agua
      t.string :verdura
      t.string :ensalada
      t.integer :tick
      t.boolean :pecho
      t.boolean :dieta_sana
      t.integer :motivacion
      t.text :desayuno1
      t.text :desayuno2
      t.text :desayuno3
      t.text :almuerzo
      t.text :almuerzo2
      t.text :almuerzo3
      t.text :cena1
      t.text :cena2
      t.text :cena3
      t.text :snacks1
      t.text :snacks2
      t.text :snacks3
      t.text :bebidas1
      t.text :bebidas2
      t.text :bebidas3

      t.timestamps
    end
  end
end
